name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JS
        uses: ./.github/actions/setup-js
        with:
          save-cache: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}

      - name: Run frontend checks
        run: task check

  rust:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup JS
        uses: ./.github/actions/setup-js

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: 1.95.0
          components: rustfmt, clippy

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./packages/desktop/src-tauri -> target"
          shared-key: tauri-linux
          cache-on-failure: true

      - name: Generate icons
        run: task desktop:generate:icons

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libwebkit2gtk-4.1-dev \
            libjavascriptcoregtk-4.1-dev \
            libsoup-3.0-dev \
            libgtk-3-dev \
            build-essential \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Run Rust checks
        run: |
          task desktop:rust:format:check
          task desktop:rust:clippy
